language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer install --dev

script: phpunit --coverage-text

notifications:
  email:
    - etienne.lemontreer+travis@gmail.com