language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit -c app