language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit -c app

notifications:
  email:
    - etienne.lemontreer+travis@gmail.com
