ba_boedoeh_booking:
    resource: "@BaBoedoehBookingBundle/Controller/"
    type:     annotation
    prefix:   /

ba_boedoeh_admin:
    resource: "@BaBoedoehAdminBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
