<?php

namespace BaBoedoeh\BookingBundle\Entity;

/**
 * BungalowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BungalowRepository extends \Doctrine\ORM\EntityRepository
{
}
